DROP TABLE IF EXISTS [Episodes];
CREATE TABLE [Episodes] (
  [episode_id] INTEGER NOT NULL ON CONFLICT FAIL PRIMARY KEY ON CONFLICT REPLACE, 
  [patient_id] TEXT NOT NULL ON CONFLICT FAIL, 
  [intake_time] DATETIME NOT NULL ON CONFLICT FAIL, 
  [meg] BOOLEAN, 
  [triage_time] DATETIME, 
  [triage_level] INTEGER)
;
